name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: true

    - name: Build and Push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:latest
        cache-from: type=registry,ref=${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}:buildcache,mode=max
